<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Produtividade extends Model
{
 use HasFactory;

 public function executores($emp)
 {
   $bindings = ['var1' => $emp, 'var2' => $emp, 'var3' => $emp  ];

  $sql = "
  SELECT substring(X.NMEXECUTOR from 1 for position(' ', X.NMEXECUTOR)-1) NMEXECUTOR, SUM(X.HOJE) HOJE, SUM(X.ONTEM) ONTEM, SUM(X.ANTEONTEM) ANTEONTEM
  FROM (
     SELECT E.NMEXECUTOR, COUNT(I.ID) HOJE, 0 ONTEM, 0 ANTEONTEM
     FROM ESCAREACAOPNEU I
     INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
     INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
     WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE-4
      AND I.ST_ETAPA = 'F'
      AND PP.IDEMPRESA = :var1
     GROUP BY  E.NMEXECUTOR
     HAVING COUNT(I.ID) > 5

  UNION ALL

     SELECT E.NMEXECUTOR, 0 HOJE, COUNT(I.ID) ONTEM, 0 ANTEONTEM
     FROM ESCAREACAOPNEU I
     INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
     INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
    WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE-5
      AND I.ST_ETAPA = 'F'
      AND PP.IDEMPRESA = :var2
     GROUP BY  E.NMEXECUTOR
     HAVING COUNT(I.ID) > 5

  UNION ALL

     SELECT E.NMEXECUTOR, 0 HOJE, 0 ONTEM, COUNT(I.ID) ANTEONTEM
     FROM ESCAREACAOPNEU I
     INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
     INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
     INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
     INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
     WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE-6
      AND I.ST_ETAPA = 'F'
      AND PP.IDEMPRESA = :var3
     GROUP BY  E.NMEXECUTOR
     HAVING COUNT(I.ID) > 5
  ) X
  GROUP BY X.NMEXECUTOR
  ORDER BY HOJE DESC
        ";

  return DB::connection('firebird')->select($sql, $bindings);

 }

}
