<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Produtividade extends Model
{
 use HasFactory;

 public function executores()
 {

  $sql = "
        SELECT X.NMEXECUTOR, SUM(X.HOJE) HOJE, SUM(X.ONTEM) ONTEM, SUM(X.ANTEONTEM) ANTEONTEM
        FROM (
           SELECT E.NMEXECUTOR, COUNT(I.ID) HOJE, 0 ONTEM, 0 ANTEONTEM
           FROM ESCAREACAOPNEU I
           INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
           INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
           INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
           INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
           WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE
            AND I.ST_ETAPA = 'F'
            AND PP.IDEMPRESA IN (1,2,3)
           GROUP BY  E.NMEXECUTOR
           HAVING COUNT(I.ID) > 5

        UNION ALL

           SELECT E.NMEXECUTOR, 0 HOJE, COUNT(I.ID) ONTEM, 0 ANTEONTEM
           FROM ESCAREACAOPNEU I
           INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
           INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
           INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
           INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
          WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE-1
            AND I.ST_ETAPA = 'F'
            AND PP.IDEMPRESA IN (1,2,3)
           GROUP BY  E.NMEXECUTOR
           HAVING COUNT(I.ID) > 5

        UNION ALL

           SELECT E.NMEXECUTOR, 0 HOJE, 0 ONTEM, COUNT(I.ID) ANTEONTEM
           FROM ESCAREACAOPNEU I
           INNER JOIN EXECUTORETAPA E ON (I.IDEXECUTOR = E.ID)
           INNER JOIN ORDEMPRODUCAORECAP OPR ON (OPR.ID = I.IDORDEMPRODUCAORECAP)
           INNER JOIN ITEMPEDIDOPNEU IPP ON (IPP.ID = OPR.IDITEMPEDIDOPNEU)
           INNER JOIN PEDIDOPNEU PP ON (PP.ID = IPP.IDPEDIDOPNEU)
           WHERE CAST(I.DTFIM AS DATE) = CURRENT_DATE-2
            AND I.ST_ETAPA = 'F'
            AND PP.IDEMPRESA IN (1,2,3)
           GROUP BY  E.NMEXECUTOR
           HAVING COUNT(I.ID) > 5
        ) X
        GROUP BY X.NMEXECUTOR
        ORDER BY HOJE DESC
        ";

  return  DB::connection('firebird')->select($sql);

 }

}
